views/account.py
# coding:utf-8
from functools import wraps
from flask import abort,Blueprint,render_template,redirect,request,url_for,flash,current_app
from _helpers import login_manager,MaxinObject,cache
from flask.ext.login import current_user,login_user,login_required,logout_user
from lolipop.models import User,Profile
from lolipop.form import RegisterForm,LoginForm,ProfileForm

bp = Blueprint('account',__name__)

def permission_limit(func):
    @wraps(func)
    def decorated_view(*args,**kwargs):
        abort(404)
    return decorated_view

def admin_required(func):
    @wraps(func)
    def decorated_view(*args,**kwargs):
        try:
            if not current_user.id == 1:
                abort(403)
            return func(*args,**kwargs)
        except AttributeError:
            abort(403)
    return decorated_view

@login_manager.user_loader
def load_user(userid):
    return User.query.get_or_404(userid)

@bp.route('/signup',methods=["GET","POST"])
def signup():
    if current_user is not None and current_user.is_authenticated():
        return redirect(url_for('.profile',uid = current_user.id))
    #next_url = request.args.get('next',url_for('.profile'))
    #token = request.args.get('token')
    #if token:
    #    user = verify_auth_token(token,1)
    #    if not user:
    #        flash(u'无效用户','error')
    #        return redirect(next_url)
    #    user.save()
    #    login_user(user)
    #    return redirect(next_url)

    form = RegisterForm()
    if form.validate_on_submit():
        user = form.save()
        #profile = Profile(user.id)
        #wait_verify = redis.set(user.username,True)
        #if not wait_verify:
        #    user.save()
        #    Profile.get_or_create(user.id)
        #    login_user(user)
        #    return redirect(next_url)
        Profile.get_or_create(user.id)
        login_user(user)
        cache.clear()
        flash(("Thanks for your registering"),"success")
        return redirect(url_for('index.index'))
    return render_template('account/signup.html',form=form)

@bp.route('/signin',methods=["GET","POST"])
def signin():
    if current_user is not None and current_user.is_authenticated():
        return redirect(url_for('.profile',uid=current_user.id))
    form = LoginForm()
    if form.validate_on_submit():
        user,authenticated=User.authenticate(form.account.data,form.password.data)
        if user and authenticated:
            
            login_user(user,remember = form.remember_me.data)
            cache.clear()
            return redirect(request.args.get("next") or url_for('index.index'))
    return render_template("account/signin.html",form=form)

@bp.route('/logout')
@login_required
def logout():
    try:
        current_app.config['ONLINEUSERS'].remove(current_user.id)
    except KeyError:
        pass
    logout_user()
    flash(("Logged out"),"success")
    return redirect(url_for('index.index'))

@bp.route('/profile/uid=<int:uid>',methods=['GET','POST'])
@login_required
def profile(uid):
    user = current_user
    profile = Profile.get_or_create(uid)
    
    # There are some trick codes,it is ugly
    # but,it is run well
    obj = MaxinObject()
    obj_dict = {}

    profile_dict = profile.__dict__
    user_dict = user.__dict__
    obj_dict.update(profile_dict)
    obj_dict.update(user_dict)
    for key in obj_dict:
        obj.__setattr__(key,obj_dict[key])
    form = ProfileForm(obj=obj)
    #next_url = request.args.get('next',url_for('.setting')) 
    if form.validate_on_submit():
        form.populate_obj(profile)
        profile.save()
        return redirect(url_for('.profile',uid=uid))
    return render_template('account/profile.html',form=form,profile=profile)

views/admin.py
# coding:utf-8
from flask import Blueprint,request,render_template,flash,current_app,redirect,url_for
from views.account import admin_required
from _helpers import force_int,fill_object
from lolipop.models import User,Profile
from lolipop.form import NodeForm
import codecs,os

bp = Blueprint('admin',__name__)

@bp.route('/',methods=['GET','POST'])
@admin_required
def dashboard():
    if request.method == 'POST':
        save_sidebar_notice(request.form.get('content',None))
        return redirect(url_for('.dashboard'))
    page = force_int(request.args.get('page', 1), 0)
    if not page:
        return abort(404)
    form = NodeForm()
    paginator = User.query.order_by(User.id.desc()).paginate(page)
    profiles = Profile.query.order_by(Profile.id).paginate(page).items
    paginator.itmes = fill_object(paginator.items,profiles,'avatar')

    return render_template(
        'admin/dashboard.html',
        paginator=paginator,
        form = form,
    )

def save_sidebar_notice(content):
    with codecs.open(os.path.join(current_app.config['ROOTDIR'],'announcement'),'w','utf-8','strict') as f:
        f.write(content)

def load_sidebar_notice():
    with codecs.open(os.path.join(current_app.config['ROOTDIR'],'announcement'),'r','utf-8','strict') as f: 
        content = f.read()
        return content

views/node.py
from flask import redirect,render_template,url_for,flash,abort,request,Blueprint
from _helpers import force_int,cache,fill_with_user,fill_with_node
from lolipop.form import NodeForm,CreateForm
from lolipop.models import Node,Topic
from flask.ext.login import current_user
from views.account import admin_required

bp = Blueprint("node",__name__)

@bp.route('/')
def nodes():
    nodes = Node.query.order_by(Node.id.desc()).all()
    return render_template('node/nodes.html',nodes = nodes)

@bp.route('/<urlname>',methods=('GET','POST'))
@cache.cached(timeout=50)
def view(urlname):
   node = Node.query.filter_by(title=urlname).first_or_404() 
   page = force_int(request.args.get('page',1),0)
   if not page:
       return abort(404)
   paginator = Topic.query.filter_by(node_id=node.id).order_by(Topic.id.desc()).paginate(page,10)
   paginator.items = fill_with_node(fill_with_user(paginator.items))
   form = None
   if current_user is not None and current_user.is_authenticated():
       form = CreateForm()
   return render_template('node/view.html',form=form,node=node,paginator=paginator)

@bp.route('/create',methods=['GET','POST'])
@admin_required
def create():
    form = NodeForm()
    if form.validate_on_submit():
        node = form.save()
        cache.clear()
        return redirect(url_for('.view',urlname=node.title))
    return render_template('node/create.html',form=form,current_user = current_user)

@bp.route('/<urlname>/edit',methods=['GET','POST'])
@admin_required
def edit(urlname):
    node = Node.query.filter_by(title=urlname).first_or_404()
    form = NodeForm(obj=node)
    if form.validate_on_submit():
        form.populate_obj(node)
        node.save()
        cache.clear()
        return redirect(url_for('.view',urlname=node.title))
    return render_template('node/edit.html',form=form,node=node,current_user=current_user)

templates/snippet/footer.html
<footer id="footer">
  <div class="container clearfix">
    <div class="muted links pull-left">
      <span class="sep">&middot;</span>
      <a href="https://github.com/SeavantUUz/kutoto_flask">代码</a>
      <span class="sep">&middot;</span>
      <a href="http://blog.kochiya.me">作者</a>
      <span class="sep">&middot;</span>
      <a href="https://github.com/pythoncn/june">june</a>
    </div>
    <p class="muted credit pull-right">
    Powered by <a href="http://blog.kochiya.me">AprocySanae</a>, And specal thanks to <a href="https://github.com/pythoncn/june">june</a>
    </p>
  </div>
</footer>

templates/snippet/google-analytics.html
{% if config.SITE_ANALYTICS %}
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', '{{config.SITE_ANALYTICS}}']);
_gaq.push(['_trackPageview']);
_gaq.push(['_trackPageLoadTime']);
{% if g.user %}
_gaq.push(['_setCustomVar', 1, 'UserType', 'Member', 2]);
{% else %}
_gaq.push(['_setCustomVar', 1, 'UserType', 'Guest', 2]);
{% endif %}
(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = 'https://ssl.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
{% endif %}

templates/snippet/markdown-help.html
{% raw %}
<h5>Strong and Emphasize</h5>

<pre><code>*emphasize*    **strong**
_emphasize_    __strong__
</code></pre>

<h5>Links</h5>

<p>Inline links:</p>

<pre><code>[link text](http://url.com/ "title")
[link text](http://url.com/)
&lt;http://url.com&gt;
</code></pre>

<p>Reference-style links:</p>

<pre><code>[link text][id]

    [id]: http://url.com "title"
</code></pre>

<h5>Images</h5>

<p>Inline images:</p>

<pre><code>![alt text](http://path/to/img.jpg "title")
![alt text](http://path/to/img.jpg)
</code></pre>

<p>Reference-style links:</p>

<pre><code>![alt text][id]

    [id]: http://path/to/img.jpg "title"
</code></pre>

<h5>Headers</h5>

<p>Atx-style headers:</p>

<pre><code># h1
## h2
### h5
…
</code></pre>

<p>Closing # are optional.</p>

<pre><code># h1 #
## h2 ##
…
</code></pre>

<h5>Lists</h5>

<p>Ordered list without paragraphs:</p>

<pre><code>1. foo
2. bar
</code></pre>

<p>Unordered list with paragraphs:</p>

<pre><code>* A list item.

  With multiple paragraphs.

* bar
</code></pre>

<p>You can nest them:</p>

<pre><code>* Abacus
  * anser
* Bubbles
  1. bunk
  2. bupkis
     * bar
  3. burper
* Cunning
</code></pre>


<h5>Blockquotes</h5>

<pre><code>&gt; Email-style angle brackets
&gt; are used for blockquotes.

&gt; &gt; And, they can be nested.

&gt; #### Headers in blockquotes
&gt; 
&gt; * You can quote a list.
&gt; * Etc.
</code></pre>

<h5>Code Spans</h5>

<pre><code>`&lt;code&gt;` spans are delimited
by backticks.

You can include literal backticks
like `` `this` ``.
</code></pre>

<h5>Code Blocks</h5>

<p>Indent at least 4 spaces or 1 tab.</p>

<pre><code>This is a normal paragraph

    this is code block
</code></pre>

<p>Fenced code block with three `.</p>
<pre><code>This is a normal paragraph

```
this is code block
```

```python
def foo():
    return True
```
</code></pre>

<h5>Manual Line Breaks</h5>

<p>End a line with two or more spaces:</p>

<pre><code>Roses are red, [space][space]
Violets are blue. [space][space]
</code></pre>
{% endraw %}

templates/snippet/nav-dropmenu.html
<ul class="nav pull-right">
  {%- if current_user!=None and current_user.is_authenticated() %}
  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">我 <b class="caret"></b></a>
  <ul class="dropdown-menu" role="menu">
    <li class="divider"></li>
    {% if current_user.id == 1 %}<li><a href="{{url_for('admin.dashboard')}}">后台管理</a></li>{% endif %}
    <li><a href="{{url_for('account.profile',uid=current_user.id)}}">个人资料</a></li>    
    <li><a href="{{url_for('account.logout')}}">登出</a></li>
  </ul>
</li>
{%- else %}
  <li><a href="{{url_for('account.signup')}}">注册</a></li>
  <li><a href="{{url_for('account.signin')}}">登录</a></li>

{%- endif %}
</ul>

templates/snippet/sidebar.html
<div class="module">
    <div class="module-header inner">
    <strong>关注节点</strong>
  </div>
  <div class="module-body inner">
            <ul>
        {% with nodes = getNodes() %}  
        {% if nodes %}

        {% for item in nodes %}
        <li><a href="{{url_for('node.view', urlname=item.title)}}">{{item.title}}</a></li>
        {% endfor %}

        {% endif %}
        {% endwith %}
                </ul>
  </div>
</div>

<div class="module">
  <div class="module-header inner">
    <strong>小伙伴们</strong>
  </div>
  <div class="module-body inner">
        {% with site_sidebar = load_sidebar_notice() %}
        {% if site_sidebar %}
        {{ site_sidebar|renderToGFM|safe }}
        {% endif %}
        {% endwith %}
  </div>
</div>