views/node.py
from flask import redirect,render_template,url_for,flash,abort,request,Blueprint
from _helpers import force_int,cache,fill_with_user,fill_with_node
from lolipop.form import NodeForm,CreateForm
from lolipop.models import Node,Topic
from flask.ext.login import current_user
from views.account import admin_required

bp = Blueprint("node",__name__)

@bp.route('/')
def nodes():
    nodes = Node.query.order_by(Node.id.desc()).all()
    return render_template('node/nodes.html',nodes = nodes)

@bp.route('/<urlname>',methods=('GET','POST'))
@cache.cached(timeout=50)
def view(urlname):
   node = Node.query.filter_by(title=urlname).first_or_404() 
   page = force_int(request.args.get('page',1),0)
   if not page:
       return abort(404)
   paginator = Topic.query.filter_by(node_id=node.id).order_by(Topic.id.desc()).paginate(page,10)
   paginator.items = fill_with_node(fill_with_user(paginator.items))
   form = None
   if current_user is not None and current_user.is_authenticated():
       form = CreateForm()
   return render_template('node/view.html',form=form,node=node,paginator=paginator)

@bp.route('/create',methods=['GET','POST'])
@admin_required
def create():
    form = NodeForm()
    if form.validate_on_submit():
        node = form.save()
        cache.clear()
        return redirect(url_for('.view',urlname=node.title))
    return render_template('node/create.html',form=form,current_user = current_user)

@bp.route('/<urlname>/edit',methods=['GET','POST'])
@admin_required
def edit(urlname):
    node = Node.query.filter_by(title=urlname).first_or_404()
    form = NodeForm(obj=node)
    if form.validate_on_submit():
        form.populate_obj(node)
        node.save()
        cache.clear()
        return redirect(url_for('.view',urlname=node.title))
    return render_template('node/edit.html',form=form,node=node,current_user=current_user)

views/topic.py
# coding: utf-8
from flask import Blueprint,render_template,redirect,abort,url_for,request,flash
from flask.ext.login import current_user,login_required
from jinja2 import TemplateNotFound
from lolipop.models import Post,Topic,User,Node
from lolipop.form import ReplyForm,CreateForm
from _helpers import force_int,fill_with_user,fill_with_node,cache,redis,MaxinObject
from views.account import admin_required

bp = Blueprint('topic',__name__)

@bp.route('/')
@cache.cached(timeout=50)
def topics():
    '''To list all topics'''
    page = force_int(request.args.get('page',1),0)
    if not page:
        return abort(404)
    paginator = Topic.query.order_by(Topic.date_created.desc()).paginate(page,15)
    paginator.items=fill_with_node(fill_with_user(paginator.items))
    return render_template('topic/topics.html',paginator=paginator,endpoint='topic.topics')

@bp.route('/latest')
@cache.cached(timeout=50)
def latest():
    '''list all topics by latest time'''
    page = force_int(request.args.get('page',1),0) 
    if not page:
        return abort(404)
    paginator = Topic.query.order_by(Topic.id.desc()).paginate(page,15)
    paginator.items=fill_with_node(fill_with_user(paginator.items))
    return render_template('topic/topics.html',paginator=paginator,endpoint='topic.latest')

@bp.route('/<int:uid>',methods=('GET','POST'))
#@cache.cached(timeout=50)
def view(uid):
    page = force_int(request.args.get('page',1),0)
    if not page:
        return abort(404)
    paginator = Post.query.filter_by(topic_id=uid).paginate(page,15)
    paginator.items = fill_with_user(paginator.items)
    topic = Topic.query.get_or_404(uid)
    form = None
    if current_user is not None and current_user.is_authenticated():
        form = ReplyForm()
    return render_template('topic/view.html',form=form,topic=topic,paginator=paginator)
    
@bp.route('/create/<urlname>',methods=('GET','POST'))
@login_required
def create(urlname):
    node = Node.query.filter(Node.title == urlname).first_or_404()
    form = CreateForm()
    if form.validate_on_submit():
        form.save(node,current_user)
        cache.clear()
        return redirect(url_for('.topics'))
    return render_template('topic/create.html',form=form)

@bp.route('/<int:uid>/reply',methods=['GET','POST'])
def reply(uid):
    '''
    you could reply or post.The only difference
    is whether a pid would be passed.
    if you passed a pid,you should content a 
    link to the form.
    '''
    topic = Topic.query.get_or_404(uid)
    pid = force_int(request.args.get('pid', 0), 0)
    # if pid:
    #     post = Post.query.get_or_404(pid)
    #     user_id = post.user_id
    #     user_key = 'user-replied/%d' % user_id
    #     p = redis.pipeline()
    #     p.sadd(user_key,uid)
    #     p.execute()
    #     obj = MaxinObject()
    #     pre_content = '@'+User.query.get_or_404(user_id).username+' ' 
    #     #obj.__setattr__('content',pre_content) 
    #     form = ReplyForm()
    #     form.content = pre_content
    # else:
    form = ReplyForm()
    if form.validate_on_submit():
        form.save(current_user,topic)
        cache.clear()
    else:
        flash(('Missing content'),'error')
    return redirect(url_for('.view',uid=uid))

@bp.route('/delete/<int:uid>')
@admin_required
def delete(uid):
    topic = Topic.query.get_or_404(uid)
    topic.delete()
    return redirect(url_for('.topics'))

templates/node/create.html
{% extends "layout.html" %}
{% from "macro/form.html" import horizontal_field, horizontal_form_button %}

{% block subtitle %}创建节点{% endblock %}

{% block content %}
<div class="module">
  <div class="module-header inner">
    <strong>创建节点</strong>
  </div>
  <form class="form-horizontal inner" method="post" action="">
    {{ form.csrf_token }}

    {{ horizontal_field(form.title, 'input-block-level') }}
    {{ horizontal_field(form.description, 'input-block-level') }}

    {{ horizontal_form_button('创建', 'btn-success') }}
  </form>
</div>
{% endblock %}

templates/node/edit.html
{% extends "layout.html" %}
{% from "macro/form.html" import horizontal_field, horizontal_form_button %}

{% block subtitle %}编辑节点{% endblock %}

{% block content %}
<div class="module">
  <div class="module-header inner">
    <strong>编辑节点</strong>
  </div>
  <form class="form-horizontal inner" method="post" action="">
    {{ form.csrf_token }}

    {{ horizontal_field(form.title, 'input-block-level') }}
    {{ horizontal_field(form.description, 'input-block-level') }}

    {{ horizontal_form_button('保存', 'btn-success') }}
  </form>
</div>
{% endblock %}

templates/node/nodes.html
{% extends "layout.html" %}

{% block subtitle %}节点{% endblock %}

{% from "macro/ui.html" import nav %}

{% block nav %}
{{ nav('node') }}
{% endblock %}



{% block content %}
{% from "macro/ui.html" import node_list %}
<div class="module">
  <div class="module-header inner">
    <strong>节点</strong>
  </div>
  <div class="module-body">
    {{ node_list(nodes) }}
  </div>
</div>
{% endblock %}

templates/node/view.html
{% extends "layout.html" %}

{% block subtitle %}节点{% endblock %}

{% from "macro/form.html" import render_field %}
{% from "macro/ui.html" import nav %}

{% block nav %}
{{ nav('node') }}
{% endblock %}

{% block declaration %}
<div class="module">
  <div class="module-header inner">
    <strong>简述</strong>
  </div>
  <div class="module-body item-list">
    <div class="item hentry">
      <div class="entry-content">{{ node.description|renderToGFM|safe }}</div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
{% from "macro/ui.html" import topic_list, pagination %}
<div class="module">
  <div class="module-header inner">
    <strong>主题</strong>
  </div>
  <div class="module-body">
    {{ topic_list(paginator.items) }}
  </div>
  {% if paginator.pages > 1 %}
  <div class="module-footer inner">
    {{ pagination(paginator, url_for('node.view', urlname=node.title)) }}
  </div>
  {% endif %}
</div>

<div class="module">
  {% if form %}
  <form class="form topic-form" action="{{url_for('topic.create', urlname=node.title)}}" method="post">
    <div class="inner">
    {{ form.csrf_token }}
    {{ render_field(form.subject, 'input-block-level') }}
    {{ render_field(form.content, 'input-block-level') }}
  </div>
    <div class="form-submit text-right">
      <button class="btn btn-success">新建话题</button>
    </div>
  </form>
  {% else %}
  <div class="inner">
    <div class="alert alert-info">需要登录的说～</div>
  </div>
  {% endif %}
</div>
{% endblock %}