views/topic.py
# coding: utf-8
from flask import Blueprint,render_template,redirect,abort,url_for,request,flash
from flask.ext.login import current_user,login_required
from jinja2 import TemplateNotFound
from lolipop.models import Post,Topic,User,Node
from lolipop.form import ReplyForm,CreateForm
from _helpers import force_int,fill_with_user,fill_with_node,cache,redis,MaxinObject
from views.account import admin_required

bp = Blueprint('topic',__name__)

@bp.route('/')
@cache.cached(timeout=50)
def topics():
    '''To list all topics'''
    page = force_int(request.args.get('page',1),0)
    if not page:
        return abort(404)
    paginator = Topic.query.order_by(Topic.date_created.desc()).paginate(page,15)
    paginator.items=fill_with_node(fill_with_user(paginator.items))
    return render_template('topic/topics.html',paginator=paginator,endpoint='topic.topics')

@bp.route('/latest')
@cache.cached(timeout=50)
def latest():
    '''list all topics by latest time'''
    page = force_int(request.args.get('page',1),0) 
    if not page:
        return abort(404)
    paginator = Topic.query.order_by(Topic.id.desc()).paginate(page,15)
    paginator.items=fill_with_node(fill_with_user(paginator.items))
    return render_template('topic/topics.html',paginator=paginator,endpoint='topic.latest')

@bp.route('/<int:uid>',methods=('GET','POST'))
#@cache.cached(timeout=50)
def view(uid):
    page = force_int(request.args.get('page',1),0)
    if not page:
        return abort(404)
    paginator = Post.query.filter_by(topic_id=uid).paginate(page,15)
    paginator.items = fill_with_user(paginator.items)
    topic = Topic.query.get_or_404(uid)
    form = None
    if current_user is not None and current_user.is_authenticated():
        form = ReplyForm()
    return render_template('topic/view.html',form=form,topic=topic,paginator=paginator)
    
@bp.route('/create/<urlname>',methods=('GET','POST'))
@login_required
def create(urlname):
    node = Node.query.filter(Node.title == urlname).first_or_404()
    form = CreateForm()
    if form.validate_on_submit():
        form.save(node,current_user)
        cache.clear()
        return redirect(url_for('.topics'))
    return render_template('topic/create.html',form=form)

@bp.route('/<int:uid>/reply',methods=['GET','POST'])
def reply(uid):
    '''
    you could reply or post.The only difference
    is whether a pid would be passed.
    if you passed a pid,you should content a 
    link to the form.
    '''
    topic = Topic.query.get_or_404(uid)
    pid = force_int(request.args.get('pid', 0), 0)
    # if pid:
    #     post = Post.query.get_or_404(pid)
    #     user_id = post.user_id
    #     user_key = 'user-replied/%d' % user_id
    #     p = redis.pipeline()
    #     p.sadd(user_key,uid)
    #     p.execute()
    #     obj = MaxinObject()
    #     pre_content = '@'+User.query.get_or_404(user_id).username+' ' 
    #     #obj.__setattr__('content',pre_content) 
    #     form = ReplyForm()
    #     form.content = pre_content
    # else:
    form = ReplyForm()
    if form.validate_on_submit():
        form.save(current_user,topic)
        cache.clear()
    else:
        flash(('Missing content'),'error')
    return redirect(url_for('.view',uid=uid))

@bp.route('/delete/<int:uid>')
@admin_required
def delete(uid):
    topic = Topic.query.get_or_404(uid)
    topic.delete()
    return redirect(url_for('.topics'))

views/user.py
from flask import redirect,render_template,url_for,abort,request,Blueprint,current_app
from flask.ext.login import current_user
from _helpers import force_int,fill_object,cache,get_online_users
from lolipop.models import User,Topic,Profile


bp = Blueprint("user",__name__)

@bp.route('/')
def users():
    uids = get_online_users()
    print uids
    page = force_int(request.args.get('page',1),0)
    if not page:
        return abort(404)
    paginator = User.query.filter(User.id.in_(uids)).order_by(User.id).paginate(page)
    profiles = Profile.query.filter(Profile.id.in_(uids)).order_by(Profile.id).paginate(page).items
    paginator.items = fill_object(paginator.items,profiles,'avatar','twitter')
    return render_template('user/users.html',paginator=paginator)

@bp.route('/<int:uid>')
def view(uid):
    user = User.query.filter_by(id=uid).first_or_404()
    profile = Profile.query.filter_by(id=uid).first_or_404()
    topics = Topic.query.filter_by(user_id=uid).order_by(Topic.id.desc()).limit(15)
    return render_template('user/view.html',user=user,profile=profile,topics=topics)

templates/topic/create.html
{% extends "layout.html" %}
{% from "macro/form.html" import render_field %}

{% block subtitle %}新的主题{% endblock %}

{% block main %}
<div class="row-fluid">
  <div class="span6">
    <div class="module">
      <div class="module-header inner">
        <strong>新的主题</strong>
      </div>
      <form class="form topic-form" method="post" action="">
        <div class="inner">
          {{ form.csrf_token }}

          {{ render_field(form.subject, 'input-block-level') }}
          {{ render_field(form.content, 'input-block-level') }}
        </div>
        <div class="module-footer inner text-right">
          <button class="btn btn-success">创建</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/topic/topics.html
{% extends "layout.html" %}

{% block subtitle %}主题{% endblock %}

{% from "macro/ui.html" import nav %}

{% block nav %}
{{ nav('topic') }}
{% endblock %}

{% block content %}
{% from "macro/ui.html" import topic_list,pagination %}
<div class="module">
	<div class="module-header inner">
    	<strong>主题</strong>
  	</div>
<div class="module-body">
    {{ topic_list(paginator.items) }}
</div>
{% if paginator.pages >1 %}
<div class="module-footer inner">
    {{ pagination(paginator,url_for(endpoint)) }}
</div>
{% endif %}
</div>
{% endblock %}

templates/topic/view.html
{% extends "layout.html" %}

{% block subtitle %}话题{% endblock %}

{% from "macro/form.html" import render_field %}
{% from "macro/ui.html" import topic_list, pagination, nav %}

{% block nav %}
{{ nav('topic') }}
{% endblock %}

{% block content %}
<div class="module">
  <div class="module-body item-list reply-list">
    {% if paginator.items >1 %}
    {% for item in paginator.items %}
    <div class="item hentry">
      <div class="entry-content">{{item.content|renderToGFM|safe}}</div>
      <div class="meta clearfix">
       <a href="{{url_for('user.view', uid=item.user_id)}}">{{item.username}}</a>
      <span class="sep">&middot;</span>
      <time datetime="{{item.date_created|xmldatetime}}" pubdate>{{item.date_created|timesince}}</time>
        <!-- <span class="sep">&middot;</span> -->
      <!-- <a  href="{{ url_for('topic.reply',uid=item.topic_id)}}?pid={{item.id}}"><strong>回复</strong></a> -->
                </div>
          <a class="avatar" href="{{url_for('user.view', uid=item.user_id)}}" title="{{item.username}}"><img src="{{item.avatar}}" width="30" height="30" /></a>

    </div>
    {% endfor %}
    {% else %}
    <div class="inner">
      <div class="alert alert-info">暂时还没有回复哦～</div>
    </div>
    {% endif %}
  </div>

  {% if paginator.pages > 1 %}
  <div class="module-footer inner">
    {{ pagination(paginator, url_for('topic.view', uid=topic.id)) }}
  </div>
  {% endif %}
</div>

<div class="module">
  {% if form %}
  <form class="reply-form inner" action="{{url_for('topic.reply', uid=topic.id)}}" method="post">
    {{ form.csrf_token }}
    {{ render_field(form.content, 'input-block-level') }}
    <div class="form-submit text-right">
      <button class="btn btn-success">回复</button>
    </div>
  </form>
  {% else %}
  <div class="inner">
    <div class="alert alert-info">需要登录的说～</div>
  </div>
  {% endif %}
</div>
{% endblock %}