views/focus.py
from flask import Blueprint,redirect,url_for,abort
from flask.ext.login import current_user
from lolipop.models import Node
from _helpers import redis,cache

bp = Blueprint("focus",__name__)

def nodes_id():
    if current_user is not None and current_user.is_authenticated():
        user_key = 'user-nodes/%d' % current_user.id
        return redis.smembers(user_key)

def getNodes():
    nodes = None
    uids = nodes_id()
    if uids:
        nodes = Node.query.filter(Node.id.in_(uids))
    return nodes

@bp.route('/add/<int:node_id>')
def add(node_id):
    if current_user is not None and current_user.is_authenticated():
        user_key = 'user-nodes/%d' % current_user.id
        p = redis.pipeline()
        p.sadd(user_key,node_id)
        p.execute()
    cache.clear()
    return redirect(url_for('node.nodes'))

@bp.route('/remove/<int:node_id>')
def remove(node_id):
    if current_user is not None and current_user.is_autheneticated():
        user_key = 'user-nodes/%d' % current_user.id
        p = redis.pipeline()
        p.srem(user_key,node_id)
        p.execute()
    cache.clear()
    return redirect(url_for('node.nodes'))

views/node.py
from flask import redirect,render_template,url_for,flash,abort,request,Blueprint
from _helpers import force_int,cache,fill_with_user,fill_with_node
from lolipop.form import NodeForm,CreateForm
from lolipop.models import Node,Topic
from flask.ext.login import current_user
from views.account import admin_required

bp = Blueprint("node",__name__)

@bp.route('/')
def nodes():
    nodes = Node.query.order_by(Node.id.desc()).all()
    return render_template('node/nodes.html',nodes = nodes)

@bp.route('/<urlname>',methods=('GET','POST'))
@cache.cached(timeout=50)
def view(urlname):
   node = Node.query.filter_by(title=urlname).first_or_404() 
   page = force_int(request.args.get('page',1),0)
   if not page:
       return abort(404)
   paginator = Topic.query.filter_by(node_id=node.id).order_by(Topic.id.desc()).paginate(page,10)
   paginator.items = fill_with_node(fill_with_user(paginator.items))
   form = None
   if current_user is not None and current_user.is_authenticated():
       form = CreateForm()
   return render_template('node/view.html',form=form,node=node,paginator=paginator)

@bp.route('/create',methods=['GET','POST'])
@admin_required
def create():
    form = NodeForm()
    if form.validate_on_submit():
        node = form.save()
        cache.clear()
        return redirect(url_for('.view',urlname=node.title))
    return render_template('node/create.html',form=form,current_user = current_user)

@bp.route('/<urlname>/edit',methods=['GET','POST'])
@admin_required
def edit(urlname):
    node = Node.query.filter_by(title=urlname).first_or_404()
    form = NodeForm(obj=node)
    if form.validate_on_submit():
        form.populate_obj(node)
        node.save()
        cache.clear()
        return redirect(url_for('.view',urlname=node.title))
    return render_template('node/edit.html',form=form,node=node,current_user=current_user)

views/topic.py
# coding: utf-8
from flask import Blueprint,render_template,redirect,abort,url_for,request,flash
from flask.ext.login import current_user,login_required
from jinja2 import TemplateNotFound
from lolipop.models import Post,Topic,User,Node
from lolipop.form import ReplyForm,CreateForm
from _helpers import force_int,fill_with_user,fill_with_node,cache,redis,MaxinObject
from views.account import admin_required

bp = Blueprint('topic',__name__)

@bp.route('/')
@cache.cached(timeout=50)
def topics():
    '''To list all topics'''
    page = force_int(request.args.get('page',1),0)
    if not page:
        return abort(404)
    paginator = Topic.query.order_by(Topic.date_created.desc()).paginate(page,15)
    paginator.items=fill_with_node(fill_with_user(paginator.items))
    return render_template('topic/topics.html',paginator=paginator,endpoint='topic.topics')

@bp.route('/latest')
@cache.cached(timeout=50)
def latest():
    '''list all topics by latest time'''
    page = force_int(request.args.get('page',1),0) 
    if not page:
        return abort(404)
    paginator = Topic.query.order_by(Topic.id.desc()).paginate(page,15)
    paginator.items=fill_with_node(fill_with_user(paginator.items))
    return render_template('topic/topics.html',paginator=paginator,endpoint='topic.latest')

@bp.route('/<int:uid>',methods=('GET','POST'))
#@cache.cached(timeout=50)
def view(uid):
    page = force_int(request.args.get('page',1),0)
    if not page:
        return abort(404)
    paginator = Post.query.filter_by(topic_id=uid).paginate(page,15)
    paginator.items = fill_with_user(paginator.items)
    topic = Topic.query.get_or_404(uid)
    form = None
    if current_user is not None and current_user.is_authenticated():
        form = ReplyForm()
    return render_template('topic/view.html',form=form,topic=topic,paginator=paginator)
    
@bp.route('/create/<urlname>',methods=('GET','POST'))
@login_required
def create(urlname):
    node = Node.query.filter(Node.title == urlname).first_or_404()
    form = CreateForm()
    if form.validate_on_submit():
        form.save(node,current_user)
        cache.clear()
        return redirect(url_for('.topics'))
    return render_template('topic/create.html',form=form)

@bp.route('/<int:uid>/reply',methods=['GET','POST'])
def reply(uid):
    '''
    you could reply or post.The only difference
    is whether a pid would be passed.
    if you passed a pid,you should content a 
    link to the form.
    '''
    topic = Topic.query.get_or_404(uid)
    pid = force_int(request.args.get('pid', 0), 0)
    # if pid:
    #     post = Post.query.get_or_404(pid)
    #     user_id = post.user_id
    #     user_key = 'user-replied/%d' % user_id
    #     p = redis.pipeline()
    #     p.sadd(user_key,uid)
    #     p.execute()
    #     obj = MaxinObject()
    #     pre_content = '@'+User.query.get_or_404(user_id).username+' ' 
    #     #obj.__setattr__('content',pre_content) 
    #     form = ReplyForm()
    #     form.content = pre_content
    # else:
    form = ReplyForm()
    if form.validate_on_submit():
        form.save(current_user,topic)
        cache.clear()
    else:
        flash(('Missing content'),'error')
    return redirect(url_for('.view',uid=uid))

@bp.route('/delete/<int:uid>')
@admin_required
def delete(uid):
    topic = Topic.query.get_or_404(uid)
    topic.delete()
    return redirect(url_for('.topics'))

views/user.py
from flask import redirect,render_template,url_for,abort,request,Blueprint,current_app
from flask.ext.login import current_user
from _helpers import force_int,fill_object,cache,get_online_users
from lolipop.models import User,Topic,Profile


bp = Blueprint("user",__name__)

@bp.route('/')
def users():
    uids = get_online_users()
    print uids
    page = force_int(request.args.get('page',1),0)
    if not page:
        return abort(404)
    paginator = User.query.filter(User.id.in_(uids)).order_by(User.id).paginate(page)
    profiles = Profile.query.filter(Profile.id.in_(uids)).order_by(Profile.id).paginate(page).items
    paginator.items = fill_object(paginator.items,profiles,'avatar','twitter')
    return render_template('user/users.html',paginator=paginator)

@bp.route('/<int:uid>')
def view(uid):
    user = User.query.filter_by(id=uid).first_or_404()
    profile = Profile.query.filter_by(id=uid).first_or_404()
    topics = Topic.query.filter_by(user_id=uid).order_by(Topic.id.desc()).limit(15)
    return render_template('user/view.html',user=user,profile=profile,topics=topics)

templates/macro/form.html
{%- macro render_errors(errors) %}
{%- if errors %}
<ul class="unstyled text-error">
  {%- for error in errors %}
  <li>{{error}}</li>
  {%- endfor %}
</ul>
{%- endif %}
{%- endmacro %}

{% macro render_field(field, class='') %}
{%- if field.description %}
{{field(class_=class,placeholder=field.description)}}
{%- else %}
{{field(class_=class)}}
{%- endif %}
{{ render_errors(field.errors) }}
{% endmacro %}

{% macro render_disabled_field(field, class='') %}
{%- if field.description %}
{{field(class_=class,disabled = True,placeholder=field.description)}}
{%- else %}
{{field(class_=class,disabled = True)}}
{%- endif %}
{{ render_errors(field.errors) }}
{% endmacro %}

{% macro field_class(classes, field) %}
{% if field.flags.required %}
{% set classes = classes + ' required' %}
{% endif %}
{% if field.errors %}
{% set classes = classes + ' error' %}
{% endif %}
{{ classes }}
{% endmacro %}

{%- macro vertical_field(field, class='') %}
<fieldset class="{{ field_class('form', field) }}">
  {{field.label}}
  {{ render_field(field, class) }}
</fieldset>
{%- endmacro %}


{%- macro horizontal_field(field,class='') %}
<div class="{{ field_class('control-group', field) }}">
  {{field.label(class_='control-label')}}
  <div class="controls">
    {{ render_field(field, class) }}
  </div>
</div>
{%- endmacro %}

{%- macro horizontal_disabled_field(field,class='') %}
<div class="{{ field_class('control-group', field) }}">
  {{field.label(class_='control-label')}}
  <div class="controls">
    {{ render_disabled_field(field, class) }}
  </div>
</div>
{%- endmacro %}

{%- macro horizontal_form_button(text, class='') %}
{% set class = class + ' btn' %}
<div class="control-group">
  <div class="controls">
    <button class="{{class}}">{{text}}</button>
  </div>
</div>
{%- endmacro %}

templates/macro/ui.html
{%- macro nav(current='home') %}
<ul class="nav">
  <li {% if current == 'home' %}class="active"{% endif %}><a href="/">主页</a></li>
  <li {% if current == 'topic' %}class="active"{% endif %}><a href="{{url_for('topic.topics')}}">话题</a></li>
  <li {% if current == 'node' %}class="active"{% endif %}><a href="{{url_for('node.nodes')}}">节点</a></li>
   <li {% if current == 'user' %}class="active"{% endif %}><a href="{{url_for('user.users')}}">用户</a></li>
</ul>
{%- endmacro %}

{% macro pagination(paginator, url) %}
<div class="pagination pagination-centered">
  <ul>
    {% for page in paginator.iter_pages() %}
      {% if page %}
        {% if page == paginator.page %}
          <li class="active"><span>{{page}}</span></li>
        {% else %}
          <li><a href="{{url}}?page={{page}}">{{page}}</a></li>
        {% endif %}
      {% else %}
      <li class="disabled"><span class="ellipsis">…</span></li>
      {% endif %}
    {% endfor %}
  </ul>
</div>
{% endmacro %}


{% macro topic_list(items) %}
{% if items %}
<div class="item-list">
  {% for item in items %}
  <div class="item hentry">
    <h3 class="title"><a href="{{url_for('topic.view', uid=item.id)}}">{{item.title}}</a></h3>
    <div class="meta">
        <a href="{{url_for('node.view', urlname=item.node_titile)}}"><strong>{{item.node_title}}</strong></a>

      <span class="sep">&middot;</span>
       <a href="{{url_for('user.view', uid=item.user_id)}}">{{item.username}}</a>
      <span class="sep">&middot;</span>
      <time datetime="{{item.date_created|xmldatetime}}" pubdate>{{item.date_created|timesince}}</time>
    </div>
    <a class="avatar" href="{{url_for('user.view', uid=item.user_id)}}" title="{{item.username}}"><img src="{{item.avatar}}" width="43" height="43" /></a>
  </div>
  {% endfor %}
</div>
{% else %}
<div class="inner">
  <div class="alert alert-info">
    <strong>Oops!&nbsp</strong>
    There is no topics.
  </div>
</div>
{% endif %}
{% endmacro %}

{% macro notice_list(items) %}
<div class="item-list">
  {% for item in items %}
  <div class="item hentry">
    <h3 class="title"><a href="{{url_for('notice.view', uid=item.id)}}">{{item.title}}</a></h3>
  </div>
  {% endfor %}
</div>
{% endmacro %}

{% macro node_list(items,show_button=True) %}
<div class="node-list item-list">
  {% for item in items %}
  <div class="item hentry">
    <h3 class="title"><a href="{{url_for('node.view', urlname=item.title)}}">{{item.title}}</a></h3>
    <a class="btn btn-success btn-mini" href="{{url_for('focus.add', node_id=item.id)}}">关注</a>
  </div>
  {% endfor %}
</div>
{% endmacro %}

{% macro user_list(items, show_badge=True) %}
<div class="item-list user-list">
  {% for user in items %}
  <div class="item">
      <div class="account-group">
        <img src="{{ user.avatar}}" alt="萌" />
        <a href="{{url_for('user.view', uid=user.id)}}"><strong>{{user}}</strong></a>
        <div class="meta">
          {% if user.twitter %}
                  <time>{{ user.date_joined.strftime('%Y-%m-%d') }}</time>
          <span class="sep">&middot;</span>
          <a href="https://twitter.com/{{user.twitter}}">{{user.twitter}}</a>
          {% endif %}

        </div>
      </div>
  </div>
  {% endfor %}
</div>
{% endmacro %}